-- SiteTrack: count rows where imported text columns literally contain "null" / "NULL" / "undefined"
-- Read-only. Run in phpMyAdmin > SQL tab, review the counts, then run fix_nulls.sql.

SELECT 'users.first_name' AS col, COUNT(*) AS n FROM users WHERE first_name IN ('null','NULL','undefined')
UNION ALL SELECT 'users.last_name', COUNT(*) FROM users WHERE last_name IN ('null','NULL','undefined')
UNION ALL SELECT 'users.display_name', COUNT(*) FROM users WHERE display_name IN ('null','NULL','undefined')
UNION ALL SELECT 'users.avatar_path', COUNT(*) FROM users WHERE avatar_path IN ('null','NULL','undefined')
UNION ALL SELECT 'sessions.ip', COUNT(*) FROM sessions WHERE ip IN ('null','NULL','undefined')
UNION ALL SELECT 'sessions.user_agent', COUNT(*) FROM sessions WHERE user_agent IN ('null','NULL','undefined')
UNION ALL SELECT 'trusted_devices.user_agent', COUNT(*) FROM trusted_devices WHERE user_agent IN ('null','NULL','undefined')
UNION ALL SELECT 'sites.address', COUNT(*) FROM sites WHERE address IN ('null','NULL','undefined')
UNION ALL SELECT 'sites.client_name', COUNT(*) FROM sites WHERE client_name IN ('null','NULL','undefined')
UNION ALL SELECT 'sites.job_number', COUNT(*) FROM sites WHERE job_number IN ('null','NULL','undefined')
UNION ALL SELECT 'rooms.room_name', COUNT(*) FROM rooms WHERE room_name IN ('null','NULL','undefined')
UNION ALL SELECT 'rooms.floor', COUNT(*) FROM rooms WHERE floor IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.serial_number', COUNT(*) FROM assets WHERE serial_number IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.item_type', COUNT(*) FROM assets WHERE item_type IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.brand', COUNT(*) FROM assets WHERE brand IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.model', COUNT(*) FROM assets WHERE model IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.mac_address', COUNT(*) FROM assets WHERE mac_address IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.ip_address', COUNT(*) FROM assets WHERE ip_address IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.switch_port', COUNT(*) FROM assets WHERE switch_port IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.network_patch_number', COUNT(*) FROM assets WHERE network_patch_number IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.location_in_room', COUNT(*) FROM assets WHERE location_in_room IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.patching_details', COUNT(*) FROM assets WHERE patching_details IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.notes', COUNT(*) FROM assets WHERE notes IN ('null','NULL','undefined')
UNION ALL SELECT 'assets.archived_reason', COUNT(*) FROM assets WHERE archived_reason IN ('null','NULL','undefined')
UNION ALL SELECT 'asset_photos.caption', COUNT(*) FROM asset_photos WHERE caption IN ('null','NULL','undefined')
UNION ALL SELECT 'asset_logs.previous_location', COUNT(*) FROM asset_logs WHERE previous_location IN ('null','NULL','undefined')
UNION ALL SELECT 'asset_logs.new_location', COUNT(*) FROM asset_logs WHERE new_location IN ('null','NULL','undefined')
UNION ALL SELECT 'asset_logs.notes', COUNT(*) FROM asset_logs WHERE notes IN ('null','NULL','undefined')
UNION ALL SELECT 'asset_logs.user_name', COUNT(*) FROM asset_logs WHERE user_name IN ('null','NULL','undefined')
ORDER BY n DESC;
